---
- name: Perform tasks on localhost
  hosts: http
  gather_facts: false
  become: yes
  tasks:
    - name: Copy Git SSH key to clients
      copy:
        content: "{{private}}"
        dest: /home/git/.ssh/git_ssh_key
        mode: '0600'
        owner: git
        group: git

- name: Add key to Git server
  hosts: git
  gather_facts: false
  become: yes
  tasks:


    - name: Add Git public key to authorized_keys on Git server
      lineinfile:
        line: "{{ public}}"
        dest: /home/git/.ssh/authorized_keys
        owner: git
        group: git
        mode: '0600'

