---
- name: Configure Samba Host
  hosts: cifs_hosts
  become: yes
  roles:
    - update
  tasks:
    - name: Install Samba
      apt:
        name: samba
        state: present
    - name: Create /shares/smb directory
      file:
         path: /shares/smb
         state: directory
         owner: wst
         group: wst
         mode: "0755"


    - name: Move existing smb.conf to smb.conf.old
      command: mv /etc/samba/smb.conf /etc/samba/smb.conf.old
      args:
        creates: /etc/samba/smb.conf.old
      changed_when: false  # Avoids marking the task as changed if the file already exists

    - name: Copy smb.conf from Ansible host to Samba host
      copy:
        src: files/smb.conf  # Update with your correct path
        dest: /etc/samba/smb.conf
        backup: yes
      notify: Restart smbd.service

    - name: Add Samba user with password
      changed_when: false
      expect:
        command: smbpasswd -a wst
        responses:
          'New SMB password:': 'wst'
          'Retype new SMB password:': 'wst'
  handlers:
    - name: Restart smbd.service
      service:
        name: smbd
        state: restarted

- name: Configure CIFS on Client Servers
  hosts: cifs_clients
  become: yes
  roles:
    - update
  tasks:
    - name: Install cifs-utils
      apt:
        name: cifs-utils
        state: present

    - name: Mount CIFS
      mount:
        path: /mnt/remote4
        state: mounted
        src: "//192.168.31.236/smb"
        fstype: cifs
        opts: "username=wst,password=wst,uid=wst,gid=wst,file_mode=0755,dir_mode=0755"

