---
- name: Set up Git server
  hosts: git:git-clients
  become: true
  tasks:
    - name: Update Git with apt
      apt:
        name: git
        state: latest

    - name: Create git user with home dir and bash shell
      user:
        name: git
        shell: /bin/bash
        createhome: yes

