- name: Install NTP and connect hosts
  hosts: ntp
  become: true
  roles:
    - update
  tasks:

    - name: install ntp
      apt:
        name:
           - ntp
        state: latest

    - name: Copy named.conf.local file
      copy:
        src: files/ntp.conf
        dest: /etc/ntp.conf
    
    - name: Restart NTP to apply changes
      service:
        name: ntp
        state: restarted
        enabled: yes

- name: Install and update NTP on clients
  hosts: all:!ntp
  become: true
  roles:
    - update

