- name: Install NTP and connect hosts
  hosts: ntp
  become: true
  roles:
    - update
  tasks:

    - name: install ntp
      apt:
        name:
           - ntp
        state: latest

    - name: Copy named.conf.local file
      copy:
        src: files/ntp.conf
        dest: /etc/ntp.conf
    
    - name: Restart NTP to apply changes
      service:
        name: ntp
        state: restarted
        enabled: yes

- name: Install and update NTP on clients
  hosts: all:!ntp
  become: true
  roles:
    - update
  tasks:

    - name: Setting timedatectl to no
      command: timedatectl set-ntp no
      ignore_errors: true

    - name: Add NTP entry to /etc/systemd/timesyncd.conf
      lineinfile:
        path: /etc/systemd/timesyncd.conf
        regexp: '^#NTP'
        line: 'NTP=ntp.praca.wst'
    - name: Restart systemd-timesyncd.service
      command: systemctl restart systemd-timesyncd.service

    - name: Set timezone to London
      timezone:
         name: 'Europe/London'

